ignorePatterns:
  - "dist"
parser: "@typescript-eslint/parser"
extends:
  - eslint:recommended
  - prettier
  - plugin:@typescript-eslint/recommended
rules:
  "@typescript-eslint/no-non-null-assertion": off
  no-empty: off
parserOptions:
  ecmaVersion: 2018
  sourceType: "module"
